"""Add role column to User model with default value

Revision ID: 8b6a9f0cd8c4
Revises: 
Create Date: 2024-10-30 11:33:24.449225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6a9f0cd8c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_products')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('new_quantity',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('new_price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('f_image',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=False, server_default="farmer"))   

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('f_image',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('new_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('new_quantity',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.create_table('_alembic_tmp_products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('quantity', sa.VARCHAR(), nullable=False),
    sa.Column('new_quantity', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('new_price', sa.FLOAT(), nullable=True),
    sa.Column('f_image', sa.VARCHAR(length=200), nullable=True),
    sa.Column('date_posted', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
